service: api

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: api
          method: get

plugins:
  - serverless-offline